### ISSUE TITLE
Move subscriptions to database

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/icsx5#76]
If we would move the subscriptions to an app-local database (instead of creating them directly in the Calendar Provider as calendars), we wouldn't have to rely on the Calendar Provider anymore. This would bring some beneftis:

* For authentication we already use some kind of DB (encrypted shared preferences); a real DB would allow to store authentication and other settings together with the subscription without having to use a limited number of `_SYNC` columns
* Settings wouldn't be exposed to other apps.
* Sometimes accounts are removed by devices (for instance on system upgrades). Then all subscriptions are gone. If we store them ourselves, they would still be there and the calendars can be re-created on sync.
* Same for backup (#4) – we could then just use autoFullBackup without any extra code.
* We only need to ask for calendar permissions when there are active subscriptions :)

Steps to implement:

1. Manage subscriptions locally – Room DB (or maybe shared preferences or whatever seems feasible – but I think other things than Room will again add more "dirtyness").
2. The sync worker would have to
  - create the account (if it's not already there),
  - create/update calendars from the local subscription DB,
  - sync the calendars.

**Comment by ArnyminerZ** [comment]
I've been thinking about this, and maybe the best option is to use `AccountManager` instead of Room.
1. It's lighter, and Room might be overkill for what we need it for.
2. We can simply add new data with [`setUserData`](https://developer.android.com/reference/android/accounts/AccountManager#setUserData(android.accounts.Account,%20java.lang.String,%20java.lang.String)), so we don't have the issue with limited `SYNC` columns.
3. They are secured by the system, so storing credentials won't be a problem.
4. They are [backed up](https://stackoverflow.com/a/71926558/5717211) automatically by the system, so it will solve #4 automatically.
5. Calendar permissions can be requested only when subscribing to calendars.

What do you think @rfc2822 @devvv4ever ?

**Comment by ArnyminerZ** [comment]
Together with the migration to Room, it would be great to use `suspend` functions. This helps a lot with threading, and will avoid memory overflows, and improve general performance of the app.

`@WorkerThread` and `@UiThread` annotations are really useful to take into account which functions shall be called in the main thread, and which can be called from the main one.

**Comment by ArnyminerZ** [comment]
Roadmap:
- [x] Room dependency
- [ ] Room storage
  - [ ] Subscriptions
  - [ ] Events
- [ ] Synchronization with Android Calendar Provider

**Comment by ArnyminerZ** [comment]
I've added some tests for migration at ff7518a

**Comment by ArnyminerZ** [comment]
I've been using the database version for a while, also migrating from my old setup, and haven't found any issues. Maybe we can introduce this into beta or something?

**Comment by rfc2822** [comment]
Great that it seems to work! I'd like to switch ICSx5 to database because it's really needed.

However I can't review a PR with >2000 lines and I'd like to keep an overview of the code and what has changed. We have to find a solution where the changes are in compact batches so that I have a chance to review the changes. Maybe we can have a talk at the latest at FOSDEM about this.

My idea is that I close this PR but you keep your branch. Then we could create smaller sub-issues with their own PR each and you could re-use the code from your branch. Would that be OK? That would really make it easier for me to review this step by step.

**Comment by ArnyminerZ** [comment]
Okay, maybe I can create a list with all the required changes, and then create small PRs that implement them, I understand that this PRs is unrevieweable 😅 

Also I've started to work and research a bit on #4, so it would make the changes even bigger.

There's #91 as well, I've been sketching a little bit, but this one requires much discussion, and it's not a real priority.

> Maybe we can have a talk at the latest at FOSDEM about this.

Yup, no problem, that would be great.

**Comment by ArnyminerZ** [comment]
# Implementation steps
## Phase 1 - Foundations
### Description
Creation of the new database, and all the interfaces associated with it.

At the end of this phase, the database will be available, but no data will be written to it.

### Steps
- [ ] Add Room as dependency
  - [ ] Add [ksp](https://kotlinlang.org/docs/ksp-overview.html) for symbol processing.
  - [ ] Configure schema export.
- [ ] Type converters
  - [ ] Move from storing urls as `String`s to `Uri`s. This requires a type converter for Room.
- [ ] Subscriptions storage.
  - [ ] Create a new table that stores subscriptions, it should match the current `LocalCalendar`.
  - [ ] Events will be stored like now, in the system's database.
- [ ] Credentials storage
  - [ ] Create a new table that replaces the current `CalendarCredentials`.

### Deprecations
* `CalendarCredentials` in favor of the new credentials dao.

## Phase 2 - Migration
### Description
In this phase, the migration should be finished and tested. This would not be deleting the data from the current storage, the objective is to copy it into the new database. All of this should be tested correctly.

This has to be discussed, but maybe the best migration workflow is:
1. Fetch all the calendars from the system.
2. Iterate each of them, and check if there's a matching subscription in the database.
3. If there is one, go to the next one. If there's no matching subscription, create one with the data from the calendar.

This would be performed when running the synchronization, just before fetching the respective calendar's data. This way there's no headaches for the user, and we make sure that once we start the synchronization, the migration process has been completed.

### Testing
For testing, we should add some calendars to the system, and run the synchronization. After completing, the database should contain the calendars we have manually added.

### Caveats
When the user first enters the app after migration, no subscriptions will be shown. I think we should run the synchronization when the user first opens the app, if the subscriptions list is empty. In this case, two things can happen:
1. The user comes from a clean installation, no migration should be performed, so simply the worker will run, and nothing will be done. Since it's quite a light task, there will be no problems.
2. The user needs to migrate the database. The migration will be performed, and the subscriptions updated. Maybe we can add a parameter to the worker for not running synchronization in this case, just migration.

### Steps
- [ ] Add new logic to `SyncWorker.performSync`, before running `ProcessEventsTask` on each task. Follow steps in the description.
- [ ] Add migration tests.
  - [ ] Add account attributes to `SyncWorker`. Those are by default to the current values, but used by tests since the accounts used here are not the same as in the proper app.

## Phase 3 - Implementation
### Description
In this phase, the new code will start to be implemented into the application. This means updating the `SyncWorker` to fetch the subscriptions from the new database, and `ProcessEventsTask` to process them, as well as updating the system's calendar.

Also the subscription creator should be updated to add the subscriptions to the database instead of the system.

We should use Room's Live Data objects, which would simplify a lot the code in `CalendarListActivity`.

At the end of this phase, the frontend should not be using `LocalCalendar` anywhere.

### Steps
- [ ] `AddCalendarDetailsFragment.createCalendar` should create the calendar in the database.
- [ ] `CalendarListActivity` should load subscriptions from database.
  - [ ] Create `SubscriptionListAdapter`, that will replace `CalendarListAdapter`, and uses `Subscription` instead of `LocalCalendar`.
  - [ ] Create `SubscriptionModel`, that will replace `CalendarModel`, and uses `Subscription` instead of `LocalCalendar`. It also uses Room's LiveData objects, which are more readable and easier to implement that the current approach.
- [ ] `SyncWorker.performSync` should get the subscriptions from the database and not `LocalCalendar`.
- [ ] `ProcessEventsTask` should use `Subscription` instead of `LocalCalendar`

### Deprecations
* `MainActivity.CalendarListAdapter`
* `MainActivity.CalendarModel`

## Phase 4 - Refactoring
The final phase of the implementation. Here some cleanups and roundups should be made. Maybe we can also use this phase to fix some deprecations that are around the code, such as color fetches from resources instead of `ContextCompat.getColor`.

Since Room supports suspending functions, in this phase all the functions should be moved from regular blocking calls, to suspending functions.

### Steps
- [ ] Make all the methods in `CalendarFetcher` suspending.
- [ ] Make all the methods in the subscription and credentials daos suspending.
- [ ] Fix all deprecations.
- [ ] Add custom exceptions for clearing the errors returned by `CalendarFetcher`:
  - [ ] `HttpException`
    - [ ] `HttpInvalidResponseException`
    - [ ] `HttpServerException` - 5xx
  - [ ] `IOSecurityException`
  - [ ] `MaxRedirectCountException`
- [ ] Move `DEFAULT_COLOR` from `LocalCalendar` to `Subscription`.

### Removals
Once everything works fine, we should remove all the deprecated classes, which in theory are not being used at this point.


---
What do you think @rfc2822 ? It's more or less the changes from #92 ordered a little bit, and divided into smaller steps.

**Comment by rfc2822** [comment]
Sounds like a good plan! I'll then comment in the individual PRs :)
