### ISSUE TITLE
Rewrite to Jetpack Compose

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/icsx5#91]
To experiment with Jetpack Compose (also for DAVx⁵), I'd suggest to rewrite ICSx⁵ to Jetpack Compose as a clean "sample" :)

Depends on #151

**Comment by ArnyminerZ** [comment]
Checklist:
- [ ] Subscriptions list
  - [ ] Sync interval snackbar
  - [ ] Battery optimization snackbar
  - [ ] Dark mode toggle (should we?)
- [ ] Subscription creation
  - [ ] Source selection
    - [ ] URL selection
      - [ ] URL field
      - [ ] Authentication
    - [ ] File selection (file picker)
  - [ ] Validation screen
         _do not use `ProgressDialog`, it has been deprecated, use feedback directly from the UI_
  - [ ] Details screen
    - [ ] Display name
    - [ ] Color picker
    - [ ] Ignore embedded alarms
    - [ ] Add default alarm
    - [ ] Authentication card
- [ ] Set interval dialog
- [ ] Info activity
  - [ ] [AboutLibraries](https://github.com/mikepenz/AboutLibraries) with Jetpack Compose support
- [ ] Subscription editor
  - [ ] Details screen

**Comment by ArnyminerZ** [comment]
Depends on #76

**Comment by ArnyminerZ** [comment]
A thing that must be discussed is whether to keep using Activities, or use a variant of [Jetpack Compose's navigation system](https://developer.android.com/jetpack/compose/navigation). I think that navigation would be more performant for using the app, but also having all the view models and logic in the same activity may not be the best option.

**Comment by ArnyminerZ** [comment]
# Implementation steps
## Phase I - Setup
### Description
In this phase the project is configured, and all the dependencies are added, as well as properly configuring Jetpack Compose. Even though more dependencies may be added in the following phases, the base ones will be in this one.

### Steps
- [ ] Add versions:
  - [ ] `compose` to `1.3.2`
  - [ ] `composeBom` to `2022.12.00`
- [ ] Add Jetpack Compose dependencies.
    ```groovy
    // Jetpack Compose
    def composeBom = platform("androidx.compose:compose-bom:${versions.composeBom}")
    implementation composeBom
    androidTestImplementation composeBom
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    debugImplementation 'androidx.compose.ui:ui-tooling'
    implementation 'androidx.compose.material:material-icons-extended'
    implementation 'androidx.compose.material3:material3-window-size-class'
    implementation 'androidx.compose.runtime:runtime-livedata'
    implementation 'androidx.activity:activity-compose:1.6.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.5.1'
    ```
- [ ] Set `android.buildFeatures.compose` to `true`.
- [ ] Set `android.composeOptions.kotlinCompilerExtensionVersion = versions.compose`
- [ ] Create `.ui.theme.Color.kt` which contains all the colors to be used. Note that those will be fallback colors, the best thing would be to start using [dynamic themes](https://developer.android.com/develop/ui/views/theming/dynamic-colors) that were introduced in Android 12.
- [ ] Create `ui.theme.Theme.kt` which contains the `AppTheme`, and sets the color declared in `Color` if not on Android 12.

## Phase II - Foundations
### Description
May be implemented together with Phase I. In this phase, we should design and discuss all the individual components needed by the application. Those will be packaged inside `.ui.reusable`.

### Steps
- [ ] Design `ColorCircle`. Replaces the current color circle view. Simply a view that draws a circle with the given color.
- [ ] Design `ColorPicker`. It's a button that uses `ColorCircle`, and when clicked opens a dialog with some color options to choose from. In here we might also include the system's generated dynamic colors, and a custom color picker.
- [ ] Design `LoadingBox`. Simply a progress indicator.
- [ ] Design `SwitchRow`. It's a row with a title, subtitle, and a switch at the end. Used for preferences (ignore alarms...).

# WIP - Still working

**Comment by ArnyminerZ** [comment]
@rfc2822 I've finished the first three phases of the planning for the migration. I think it's a good start to migrate the calendar list screen, which is a quite simple Activity, and it would give a good feeling about the migration process, and how it works. It's Phase III on the planning above.

I've opened #140 so you can take a look, but that's just some dependencies and theme.

**Comment by ArnyminerZ** [comment]
Some screenshots of the new subscriptions list screen migrated to Jetpack Compose:
![Screenshot_20230720-122906](https://github.com/bitfireAT/icsx5/assets/12086466/965828fd-b9b7-473c-9a3f-6d55571beff8)

![Screenshot_20230720-122902](https://github.com/bitfireAT/icsx5/assets/12086466/e4610b96-401d-4896-ae79-dd76fde19b18)

![Screenshot_20230720-122853](https://github.com/bitfireAT/icsx5/assets/12086466/55d5f893-6ff8-4ccc-87e0-494ff1413c1a)

![Screenshot_20230720-123020](https://github.com/bitfireAT/icsx5/assets/12086466/c0e5bc1d-df2f-4fd9-900f-8ede64c183a9)

The only thing that cannot be migrated are the colors of the "pull-to-refresh" spinner. It's not supported by Jetpack Compose. Just one color can be set. We can just set it to the primary blue color and call it a day
